/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tuyaux.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tuyau.geometry} material={materials.___default___} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/tuyaux.glb')
