/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
modif
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/citerne.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder078_Cylinder107.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder077_Cylinder106.geometry}
        material={materials["Material.002"]}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.NurbsCircle002.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.NurbsCircle001.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.NurbsCircle.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder076_Cylinder105.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder075_Cylinder104.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder074_Cylinder103.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder073_Cylinder102.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder072_Cylinder101.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder071_Cylinder100.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder070_Cylinder099.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder069_Cylinder098.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder068_Cylinder097.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder067_Cylinder096.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder066_Cylinder095.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder065_Cylinder094.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder064_Cylinder093.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder063_Cylinder092.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder062_Cylinder091.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder061_Cylinder090.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder060_Cylinder089.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder059_Cylinder088.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder058_Cylinder087.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder057_Cylinder086.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder056_Cylinder085.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder055_Cylinder084.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder054_Cylinder083.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder053_Cylinder082.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder052_Cylinder081.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder051_Cylinder080.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder050_Cylinder079.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder049_Cylinder078.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder048_Cylinder077.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder047_Cylinder076.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder046_Cylinder075.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder045_Cylinder074.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder044_Cylinder073.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder043_Cylinder072.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder042_Cylinder071.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder041_Cylinder070.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder040_Cylinder069.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder039_Cylinder068.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder038_Cylinder067.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder037_Cylinder066.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder036_Cylinder065.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder035_Cylinder064.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder034_Cylinder063.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder033_Cylinder062.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder032_Cylinder061.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder031_Cylinder060.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder030_Cylinder059.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder029_Cylinder058.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder028_Cylinder057.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder027_Cylinder056.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder026_Cylinder055.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder025_Cylinder054.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder024_Cylinder053.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder023_Cylinder052.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder022_Cylinder051.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder021_Cylinder050.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder020_Cylinder049.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder019_Cylinder048.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder018_Cylinder047.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder017_Cylinder046.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder016_Cylinder045.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder015_Cylinder044.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder014_Cylinder043.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder013_Cylinder042.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder012_Cylinder041.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder011_Cylinder040.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder010_Cylinder039.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder009_Cylinder038.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder008_Cylinder037.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder007_Cylinder036.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder006_Cylinder035.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder005_Cylinder034.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder004_Cylinder033.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder003_Cylinder032.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials.None}
        position={[-1.14, -7.15, 3.94]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group position={[-1.14, -7.15, 3.94]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cylinder005_1.geometry}
          material={materials["None_kulit_pohon_1.jpg"]}
        />
        <mesh
          geometry={nodes.Cylinder005_2.geometry}
          material={materials["None_ujung_pohon_1.jpg"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/citerne.glb");
