/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/station12.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} position={[-4.45, 0, -4.4]} scale={[1.74, 1.31, 1.74]} />
      <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[-3.76, 0, 0.79]} scale={[2.32, 1.75, 2.32]} />
      <mesh geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} position={[0.73, 0, -1.76]} scale={[1.74, 1.31, 1.74]} />
      <mesh geometry={nodes.Circle006.geometry} material={nodes.Circle006.material} position={[0.74, 0, -1.79]} scale={1.62} />
      <mesh geometry={nodes.Circle007.geometry} material={nodes.Circle007.material} position={[0.74, 0.59, -1.79]} scale={1.62} />
      <mesh geometry={nodes.Circle008.geometry} material={nodes.Circle008.material} position={[-4.44, 0.03, -4.41]} scale={1.57} />
      <mesh geometry={nodes.Circle009.geometry} material={nodes.Circle009.material} position={[-4.44, 0.53, -4.41]} scale={1.57} />
      <mesh geometry={nodes.Circle010.geometry} material={nodes.Circle010.material} position={[-4.45, 0.49, -4.4]} scale={[0.87, 1.14, 0.87]} />
      <mesh geometry={nodes.Circle011.geometry} material={nodes.Circle011.material} position={[-3.77, 0.07, 0.78]} scale={2.09} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[1.34, 0.15, 4.66]} scale={[1.47, 1.25, 2.46]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[0.68, 0.9, -1.78]} rotation={[3.13, 0, 0]} scale={[0.68, 0.57, 1.13]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.001']} position={[-4.41, 0.97, -4.38]} scale={[1.18, 0.6, 1.97]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.001']} position={[-3.63, 0.75, 0.97]} scale={[3.39, 1.38, 5.67]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-0.27, 0.86, 3.47]} rotation={[0.51, -0.57, -1.28]} scale={[0.1, 2.12, 0.11]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[1.48, 0.4, 4.75]} rotation={[0, 0.51, 3.14]} scale={[0.13, 0.78, 0.14]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[-0.97, 0.24, -0.62]} rotation={[0.44, 0.49, -1.78]} scale={[0.12, 1.53, 0.12]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[0.68, 0.25, -7.11]} rotation={[1.57, 1.14, 3.14]} scale={[0.12, 4.02, 0.12]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[-1.88, 0.28, -3.17]} rotation={[0.47, -0.39, -1.39]} scale={[0.12, 1.53, 0.12]} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-4.32, 0.59, 0]} rotation={[0, 0.6, 0]} scale={[0.38, 0.38, 1.17]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.002']} position={[1.34, 0.11, 4.66]} scale={[1.47, 1.25, 2.46]} />
    </group>
  )
}

useGLTF.preload('/station12.glb')
