/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/station.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FabConvertcom_sans.geometry} material={materials['Default OBJ']} position={[3.57, 3.04, 41.83]} rotation={[0.31, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/station.glb')
