/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/combinaison.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.all_1.geometry} material={materials.___default___} />
        <mesh geometry={nodes.all_2.geometry} material={materials.material02} />
        <mesh geometry={nodes.all_3.geometry} material={materials.material03} />
      </group>
    </group>
  )
}

useGLTF.preload('/combinaison.glb')
